### PR TITLE
Merge PMDK to Master

### PR DESCRIPTION
**Pull request by pyrito**
### Reason for this PR
Wanted to integrate PMDK changes to the master branch to ensure recoverability of data structures allocated in persistent memory. Currently still working on P-CLHT. Transactions are included but are yet to be verified. See issue #5 

### How to enable PM?
1. Install PMDK
```$ git clone https://github.com/pmem/pmdk.git 
$ cd pmdk
$ git checkout tags/1.6
$ make -j
$ cd ..  
```
2. Emulate PM with Ext4-DAX mount
```$ sudo mkfs.ext4 -b 4096 -E stride=512 -F /dev/pmem0
$ sudo mount -o dax /dev/pmem0 /mnt/pmem
```

3.  Set pool_size and pool name in clht_lb_res.c. TODO: instructions to set up environment variables instead.

4. Make accordingly and run the example. 

### Checklist

- [ ] Changes are clean and readable; make logical sense
- [ ] Changes are correct, passes tests
- [ ] API changes are reflected in README
- [ ] Any required documentation is changed explicitly

### CODE REVIEW

**Review by vijay03 — CHANGES_REQUESTED** [review]
Could we change README.md to explain how to use the pmdk branch please? 

Could we also add a new pmdk.md to explain the porting effort at a high level?

**Review by SeKwonLee — CHANGES_REQUESTED** [review]
1. Need changes to properly use PMDK transactions or to employ non-transactional APIs instead only to resolve memory leak problems. There are two separate APIs provided by libpmemobj: non-transactional API and transactional. If you employ transactional API across the entire range of updates, we don't need to employ RECIPE conversions at all such as manually adding flushes after each atomic store. PMDK transaction would transparently handle everything to ensure the crash-consistent updates of data structures by using undo logging. Instead of employing transactional API, we may be able to use mini-transactional features provided in non-transactional APIs to handle memory leak problems. (Please check following these links: [link1,](https://pmem.io/2015/06/17/tx-alloc.html) [link2](https://pmem.io/2015/06/18/ntx-alloc.html), [link3](https://pmem.io/pmdk/manpages/linux/v1.5/libpmemobj/pmemobj_alloc.3)).

2. Another issue we need to address is the default PMDK pointer size (16 bytes). Different from traditional dynamic 8-byte pointers, libpmemobj uses 16-byte pointers consisting of uuid and offset, which indicate the universal identifier (8 bytes) of memory-mapped files and the offset (8 bytes) from the starting virtual address of the memory-mapped file respectively.  If we simply replace 8-byte pointers with 16-byte PMDK pointers, we can lose the benefits of the cache-efficient layout of original RECIPE indexes. For example, in our current modification, we simply replace the "next" pointer in bucket_t structure with PMEMoid (16bytes) type variable. After this modification, the bucket size is changed from 64 bytes (cache line size) to 72 bytes, so this will lead bucket allocations unaligned by cache lines. uuid is used to distinguish different memory pools and should be employed for the specific applications allocating objects from multiple memory pools. However, as RECIPE indexes only need to use a single memory pool, we can initialize uuid globally at program startup and can store offsets only as pointers in the objects of data structures.

**Comment by vijay03** [comment]
Hi @pyrito, I think I had a different pull request in mind, just talking about the existence of the PMDK branch in README + explaining how to setup and use PMDK with Recipe. The actual details of the implementation can stay within this branch, so regardless of the implementation, master's README.md should have a pointer to this branch.

**Comment by pyrito** [comment]
Hi @vijay03 ,

Was your intention to have another branch with README modifications instead?

**Comment by vijay03** [comment]
no, directly in master. So you would have to submit a different pull request.

**Comment by pyrito** [comment]
No need to merge the code. Branches are made to be separate.

**Pull request closed without merging**
